"""Database models for GROWELL CLINIC.

Phase 1 establishes the foundation models (users, settings, activity log).
Later phases add the clinical and financial domain models. Importing them
here ensures SQLAlchemy registers every table when ``db.create_all()`` runs.
"""
from app.models.activity_log import ActivityLog
from app.models.appointment import (
    ACTIVE_STATUSES,
    APPOINTMENT_STATUSES,
    APPOINTMENT_TYPES,
    DEFAULT_APPT_TYPE,
    STATUS_TRANSITIONS,
    VISIT_TYPE_COLORS,
    Appointment,
    VisitType,
    type_minutes,
)
from app.models.doctor_schedule import WEEKDAY_ORDER, DoctorSchedule
from app.models.schedule_exception import ScheduleException
from app.models.waitlist import WAITLIST_STATUSES, WaitlistEntry
from app.models.family import Family
from app.models.diagnosis import DIAGNOSIS_TYPES, ICD_VERSIONS, Diagnosis
from app.models.growth_record import GrowthRecord
from app.models.parent import (
    CLIENT_CATEGORIES,
    PARENT_RELATIONS,
    Parent,
)
from app.models.patient import (
    BLOOD_TYPES,
    CONSENT_TYPES,
    GENDERS,
    PROBLEM_STATUSES,
    Consent,
    Patient,
    PatientProblem,
)
from app.models.permissions import MODULES, ROLE_PERMISSIONS, ROLES
from app.models.role import Role
from app.models.setting import Setting
from app.models.user import User
from app.models.visit import (
    INVESTIGATION_STATUSES,
    VISIT_STATUSES,
    PatientAttachment,
    Visit,
    VisitInvestigation,
    VisitService,
)
from app.models.vital_signs import VitalSigns
from app.models.vaccine import (
    SETTLEMENT_REASONS,
    PatientVaccine,
    VACCINE_EVENT_TYPES,
    VACCINE_ROUTES,
    VACCINE_TYPES,
    Vaccine,
    VaccineBrand,
    VaccineBrandDose,
    VaccineScheduleDose,
    VaccineScheduleTemplate,
    VaccineSettlement,
)
from app.models.inventory import (
    LOW_STOCK_QTY,
    NEAR_EXPIRY_DAYS,
    RECEIPT_REASONS,
    Supplier,
    VaccineInventory,
)
from app.models.service import (
    COMMISSION_TYPES,
    ETA_ITEM_TYPES,
    SERVICE_CATEGORIES,
    SERVICE_TYPES,
    DoctorServiceCommission,
    Service,
    ServiceBundleItem,
    ServiceConsumable,
    service_type_for_category,
)
from app.models.invoice import (
    INVOICE_STATUSES,
    PAYMENT_METHODS,
    CashDrawerDay,
    CashierShift,
    Invoice,
    InvoiceItem,
    Payment,
    RefundRequest,
)
from app.models.payer import (
    CLAIM_STATUSES,
    COVERAGE_TYPES,
    PAYER_TYPES,
    Claim,
    ClaimItem,
    PatientCoverage,
    PayerContract,
    PayerContractRate,
    PayerEntity,
    PayerServiceRate,
)
from app.models.einvoice import EINVOICE_STATUSES, EInvoiceDocument
from app.models.expense import EXPENSE_CATEGORIES, Expense
from app.models.prescription import (
    DRUG_FORMS,
    INVESTIGATION_KINDS,
    RX_PAGE_SIZES,
    Drug,
    DrugInteraction,
    Investigation,
    Prescription,
    PrescriptionInvestigation,
    PrescriptionItem,
    RxPrintTemplate,
)
from app.models.message import (
    AUTOMATION_TYPES,
    DEFAULT_BIRTHDAY_BODY,
    MESSAGE_DIRECTIONS,
    MESSAGE_STATUSES,
    OCCASION_TYPES,
    SEND_MODES,
    SYSTEM_TEMPLATE_TYPES,
    TEMPLATE_DEFAULTS,
    TEMPLATE_VARIABLES,
    MessageLog,
    MessageTemplate,
)
from app.models.feedback import FEEDBACK_STATUSES, Feedback
from app.models.store import (
    DOC_KINDS,
    DOC_PREFIXES,
    MOVEMENT_KINDS,
    WAREHOUSE_KINDS,
    StockMovement,
    StoreDocument,
    StoreItem,
    Warehouse,
)
from app.models.purchase import PO_STATUSES, PurchaseOrder, PurchaseOrderItem
from app.models.payable import (
    SUPPLIER_PAYMENT_METHODS,
    SupplierInstallment,
    SupplierPayment,
)
from app.models.discount import DISCOUNT_TYPES, NamedDiscount
from app.models.accounting import (
    ACCOUNT_TYPES,
    Account,
    JournalEntry,
    JournalLine,
)
from app.models.device import (
    CONNECTION_TYPES,
    DEVICE_TYPES,
    IMPORT_MODES,
    DeviceMeasurement,
    DeviceStudy,
    DeviceStudyValue,
    MedicalDevice,
)

__all__ = [
    "User",
    "Setting",
    "ActivityLog",
    "Family",
    "Parent",
    "Patient",
    "PatientProblem",
    "PROBLEM_STATUSES",
    "Consent",
    "CONSENT_TYPES",
    "Appointment",
    "VisitType",
    "VISIT_TYPE_COLORS",
    "DoctorSchedule",
    "Visit",
    "VisitInvestigation",
    "VisitService",
    "PatientAttachment",
    "INVESTIGATION_STATUSES",
    "VitalSigns",
    "Diagnosis",
    "GrowthRecord",
    "ROLES",
    "Role",
    "MODULES",
    "ROLE_PERMISSIONS",
    "PARENT_RELATIONS",
    "CLIENT_CATEGORIES",
    "GENDERS",
    "BLOOD_TYPES",
    "APPOINTMENT_STATUSES",
    "APPOINTMENT_TYPES",
    "DEFAULT_APPT_TYPE",
    "type_minutes",
    "ACTIVE_STATUSES",
    "STATUS_TRANSITIONS",
    "ScheduleException",
    "WaitlistEntry",
    "WAITLIST_STATUSES",
    "WEEKDAY_ORDER",
    "VISIT_STATUSES",
    "DIAGNOSIS_TYPES",
    "ICD_VERSIONS",
    "Vaccine",
    "VaccineBrand",
    "VaccineSettlement",
    "SETTLEMENT_REASONS",
    "VaccineBrandDose",
    "VaccineScheduleTemplate",
    "VaccineScheduleDose",
    "PatientVaccine",
    "VACCINE_ROUTES",
    "VACCINE_TYPES",
    "VACCINE_EVENT_TYPES",
    "Supplier",
    "VaccineInventory",
    "NEAR_EXPIRY_DAYS",
    "LOW_STOCK_QTY",
    "RECEIPT_REASONS",
    "Service",
    "ServiceBundleItem",
    "ServiceConsumable",
    "DoctorServiceCommission",
    "SERVICE_CATEGORIES",
    "SERVICE_TYPES",
    "service_type_for_category",
    "COMMISSION_TYPES",
    "ETA_ITEM_TYPES",
    "Invoice",
    "InvoiceItem",
    "Payment",
    "CashDrawerDay",
    "CashierShift",
    "INVOICE_STATUSES",
    "PAYMENT_METHODS",
    "PayerEntity",
    "Claim",
    "ClaimItem",
    "CLAIM_STATUSES",
    "PayerServiceRate",
    "PayerContract",
    "PayerContractRate",
    "PatientCoverage",
    "PAYER_TYPES",
    "COVERAGE_TYPES",
    "EInvoiceDocument",
    "EINVOICE_STATUSES",
    "Expense",
    "EXPENSE_CATEGORIES",
    "Drug",
    "DrugInteraction",
    "Investigation",
    "Prescription",
    "PrescriptionItem",
    "PrescriptionInvestigation",
    "RxPrintTemplate",
    "DRUG_FORMS",
    "INVESTIGATION_KINDS",
    "RX_PAGE_SIZES",
    "MessageLog",
    "MessageTemplate",
    "MESSAGE_STATUSES",
    "MESSAGE_DIRECTIONS",
    "OCCASION_TYPES",
    "SEND_MODES",
    "AUTOMATION_TYPES",
    "SYSTEM_TEMPLATE_TYPES",
    "TEMPLATE_DEFAULTS",
    "TEMPLATE_VARIABLES",
    "DEFAULT_BIRTHDAY_BODY",
    "StoreItem",
    "StockMovement",
    "StoreDocument",
    "Warehouse",
    "DOC_KINDS",
    "DOC_PREFIXES",
    "WAREHOUSE_KINDS",
    "MOVEMENT_KINDS",
    "PurchaseOrder",
    "PurchaseOrderItem",
    "SupplierPayment",
    "SupplierInstallment",
    "SUPPLIER_PAYMENT_METHODS",
    "PO_STATUSES",
    "NamedDiscount",
    "DISCOUNT_TYPES",
    "Feedback",
    "FEEDBACK_STATUSES",
    "MedicalDevice",
    "DeviceMeasurement",
    "DeviceStudy",
    "DeviceStudyValue",
    "DEVICE_TYPES",
    "CONNECTION_TYPES",
    "IMPORT_MODES",
    "RefundRequest",
    "Account",
    "JournalEntry",
    "JournalLine",
    "ACCOUNT_TYPES",
]
